import type { LeaderboardEntry } from "@/types/flenqa-benchmark-types"

export const leaderboardData: LeaderboardEntry[] = [
  {
    model: "openrouter/owl-alpha",
    overall_accuracy: 1.0,
    total_samples: 150,
    n_correct: 150,
    avg_latency_ms: 20444.5,
    task_breakdown: {
      MonoRel: {
        accuracy: 1.0,
        n_samples: 50,
        n_correct: 50,
      },
      PIR: {
        accuracy: 1.0,
        n_samples: 50,
        n_correct: 50,
      },
      "Simplified RuleTaker": {
        accuracy: 1.0,
        n_samples: 50,
        n_correct: 50,
      },
    },
    rank: 1,
    display_name: "Owl Alpha",
    size: "—",
    context_window: "1M",
    family: "Owl",
  },
  {
    model: "moonshotai/kimi-k2.7-code",
    overall_accuracy: 0.9933,
    total_samples: 150,
    n_correct: 149,
    avg_latency_ms: 5568.3,
    task_breakdown: {
      MonoRel: {
        accuracy: 1.0,
        n_samples: 50,
        n_correct: 50,
      },
      PIR: {
        accuracy: 1.0,
        n_samples: 50,
        n_correct: 50,
      },
      "Simplified RuleTaker": {
        accuracy: 0.98,
        n_samples: 50,
        n_correct: 49,
      },
    },
    rank: 2,
    display_name: "Kimi K2.7 Code",
    size: "—",
    context_window: "262K",
    family: "Kimi",
  },
  {
    model: "qwen/qwen3.7-plus",
    overall_accuracy: 0.9867,
    total_samples: 150,
    n_correct: 148,
    avg_latency_ms: 7631.3,
    task_breakdown: {
      MonoRel: {
        accuracy: 1.0,
        n_samples: 50,
        n_correct: 50,
      },
      PIR: {
        accuracy: 1.0,
        n_samples: 50,
        n_correct: 50,
      },
      "Simplified RuleTaker": {
        accuracy: 0.96,
        n_samples: 50,
        n_correct: 48,
      },
    },
    rank: 3,
    display_name: "Qwen 3.7 Plus",
    size: "—",
    context_window: "1M",
    family: "Qwen",
  },
  {
    model: "qwen/qwen3.6-plus",
    overall_accuracy: 0.98,
    total_samples: 150,
    n_correct: 147,
    avg_latency_ms: 14425.3,
    task_breakdown: {
      MonoRel: {
        accuracy: 1.0,
        n_samples: 50,
        n_correct: 50,
      },
      PIR: {
        accuracy: 1.0,
        n_samples: 50,
        n_correct: 50,
      },
      "Simplified RuleTaker": {
        accuracy: 0.94,
        n_samples: 50,
        n_correct: 47,
      },
    },
    rank: 4,
    display_name: "Qwen 3.6 Plus",
    size: "—",
    context_window: "1M",
    family: "Qwen",
  },
  {
    model: "qwen/qwen3.6-flash",
    overall_accuracy: 0.9733,
    total_samples: 150,
    n_correct: 146,
    avg_latency_ms: 5036.2,
    task_breakdown: {
      MonoRel: {
        accuracy: 1.0,
        n_samples: 50,
        n_correct: 50,
      },
      PIR: {
        accuracy: 1.0,
        n_samples: 50,
        n_correct: 50,
      },
      "Simplified RuleTaker": {
        accuracy: 0.92,
        n_samples: 50,
        n_correct: 46,
      },
    },
    rank: 5,
    display_name: "Qwen 3.6 Flash",
    size: "—",
    context_window: "1M",
    family: "Qwen",
  },
  {
    model: "z-ai/glm-5.2",
    overall_accuracy: 0.96,
    total_samples: 150,
    n_correct: 144,
    avg_latency_ms: 8106.8,
    task_breakdown: {
      MonoRel: {
        accuracy: 1.0,
        n_samples: 50,
        n_correct: 50,
      },
      PIR: {
        accuracy: 0.94,
        n_samples: 50,
        n_correct: 47,
      },
      "Simplified RuleTaker": {
        accuracy: 0.94,
        n_samples: 50,
        n_correct: 47,
      },
    },
    rank: 6,
    display_name: "GLM 5.2",
    size: "—",
    context_window: "1M",
    family: "GLM",
  },
  {
    model: "google/gemini-3.5-flash",
    overall_accuracy: 0.94,
    total_samples: 150,
    n_correct: 141,
    avg_latency_ms: 3410.9,
    task_breakdown: {
      MonoRel: {
        accuracy: 0.96,
        n_samples: 50,
        n_correct: 48,
      },
      PIR: {
        accuracy: 1.0,
        n_samples: 50,
        n_correct: 50,
      },
      "Simplified RuleTaker": {
        accuracy: 0.86,
        n_samples: 50,
        n_correct: 43,
      },
    },
    rank: 7,
    display_name: "Gemini 3.5 Flash",
    size: "—",
    context_window: "1M",
    family: "Gemini",
  },
  {
    model: "ibm-granite/granite-4.1-8b",
    overall_accuracy: 0.9267,
    total_samples: 150,
    n_correct: 139,
    avg_latency_ms: 2294.5,
    task_breakdown: {
      MonoRel: {
        accuracy: 0.92,
        n_samples: 50,
        n_correct: 46,
      },
      PIR: {
        accuracy: 0.94,
        n_samples: 50,
        n_correct: 47,
      },
      "Simplified RuleTaker": {
        accuracy: 0.92,
        n_samples: 50,
        n_correct: 46,
      },
    },
    rank: 8,
    display_name: "Granite 4.1 8B",
    size: "8B",
    context_window: "131K",
    family: "Granite",
  },
  {
    model: "deepseek/deepseek-v4-flash",
    overall_accuracy: 0.92,
    total_samples: 150,
    n_correct: 138,
    avg_latency_ms: 3749.8,
    task_breakdown: {
      MonoRel: {
        accuracy: 0.92,
        n_samples: 50,
        n_correct: 46,
      },
      PIR: {
        accuracy: 0.98,
        n_samples: 50,
        n_correct: 49,
      },
      "Simplified RuleTaker": {
        accuracy: 0.86,
        n_samples: 50,
        n_correct: 43,
      },
    },
    rank: 9,
    display_name: "DeepSeek V4 Flash",
    size: "—",
    context_window: "1M",
    family: "DeepSeek",
  },
  {
    model: "deepseek/deepseek-v4-pro",
    overall_accuracy: 0.8933,
    total_samples: 150,
    n_correct: 134,
    avg_latency_ms: 5580.3,
    task_breakdown: {
      MonoRel: {
        accuracy: 0.96,
        n_samples: 50,
        n_correct: 48,
      },
      PIR: {
        accuracy: 0.94,
        n_samples: 50,
        n_correct: 47,
      },
      "Simplified RuleTaker": {
        accuracy: 0.78,
        n_samples: 50,
        n_correct: 39,
      },
    },
    rank: 10,
    display_name: "DeepSeek V4 Pro",
    size: "—",
    context_window: "1M",
    family: "DeepSeek",
  },
]
